### ISSUE TITLE
How to generate hdf5 inputs for "find_nearest_neighbors.py"

### ISSUE THREAD

**Issue by ncoudray** [AdalbertoCq/Pathology-GAN#2]
Hi - 

 First, thanks a lot for sharing your code! 
 I've been trying to run the different commands on the main page but had trouble with the last one, find_nearest_neighbors.py.
It is unclear what the input hdf5 files should be. Looking at the code, it looks like it expects 4 hdf5 files (2 for real, 2 for "generated" and for each, one "image" and one "features" hdf5).
  However, it is unclear how to obtain these hdf5 files. It looks like even for the real one, it's different from the input training or test set, and the "generated" one is also different from the one obtained from the format obtained out of the "generate_fake_samples.py" algorithm.
Could you please clarify the use of that function?

Thanks,
Best,
Nicolas

**Comment by AdalbertoCq** [comment]
Hey Nicolas, 

No problem at all!  

The script 'find_nearest_neighbors.py' uses two kinds of HDF5 files per Real/Generated, one with the images and another one with the InceptionV1 features. 

Like you say, the script 'generate_fake_samples.py' should give back a folder with the generated images but also the two HDF5 files, images and InceptionV1 features. If you have your real images into an HDF5 file to train the model, you will only need to generate the InceptionV1 features. The script 'real_features.py' should give you that. 

It is possible that there's a mismatch between the 'generate_fake_samples.py' and 'find_nearest_neighbors.py' too, I haven't used the 'find_nearest_neighbors.py' in a while.

Let me spend some time to look at it and see where the issue is, I'll get back to you. 

Thanks for bringing this up,
Adal

**Comment by ncoudray** [comment]
Hi Adal,

 thanks a lot for your quick reply and for having a look at it.

For real_features.py, I indeed get the expected file, but only if I modify the last line of the code, replacing:
`inception_tf_feature_activations(hdf5s=hdf5s, input_shape=data.training.shape[1:], batch_size=50, checkpoint_path=None)
`
with
`inception_tf_feature_activations(hdf5s=hdf5s, input_shape=data.training.shape[1:], batch_size=50)`
(not sure though if it is indeed real_features.py that needed to be changed or if it is the "models.evaluation.features" library that's not the latest one?)

 However, regarding "generate_fake_samples", it generates only one file in my case, named like this hdf5_<xx>_<yyy>_images_PathologyGAN.h5

Thanks,
Best

**Comment by AdalbertoCq** [comment]
Hey Nicolas,

I'm sorry for the late reply. 

I took a look to the scripts 'generate_fake_samples.py', 'real_features.py', 'find_nearest_neighbors.py', and others. There were some assumptions in the file naming that most likely made it not work properly. Also, as you mentioned, I had some code that was not up to date on the 'inception_tf_feature_activations'.

You should be able to run now 'generate_fake_samples.py' and get generated images with the features, and 'real_features.py' with images and features for two sets (train/test). 'find_nearest_neighbors.py' will give you the images with the generated/real closest, furthest, and random neighbors. There's also the option to provide the numbers of particular generated images through '--selected_list 20 45 1'.

Please let me know if you still have any issue.

Thanks again for bringing this up!
Adal

I have pushed the changes to the

**Comment by ncoudray** [comment]
Hi Adal,

  Thanks a lot for the update! It's greatly appreciated!

Best,
Nicolas
